- name : Configure Docker on test-server Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Updating 
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install docker -y

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : Run the health application
    command: sudo docker run -dt -p 8085:8081 vikrant246/helthimg:10
